# Power Platform Samples
# Author: Hugo Bernier
site_name: Power Platform Samples
plugins:
    - macros
    - markdownextradata
nav:
  - Samples:
    - All: samples/all.md
    - Power Fx: samples/powerfx.md
    - Power Apps: samples/powerapps.md
    - Power Automate: samples/powerautomate.md
    - Power Virtual Agent: samples/pva.md
  - Getting Started:
    - Using the Samples: gettingstarted/index.md
    - Troubleshooting: gettingstarted/troubleshooting.md
  - Contributing:
    - Contribution Guide: contributing/index.md
    - Submitting an Issue or Suggestion: contributing/issues.md
    - Forking?: contributing/forking.md
    - Creating a Sample: contributing/sample.md
    - Submitting a Pull Request: contributing/pullrequest.md
theme:
  name: 'material'
  custom_dir: 'custom_theme'
  palette:
    primary: 'pnp'
    accent: 'indigo'
  logo: 'img/pnp-samples-white.svg'
  feature:
    tabs: true
extra_css:
  - 'css/extra.css'
  - 'css/filter.css'
  - 'https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/10.0.0/css/fabric.min.css'
extra_javascript:
  - 'https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js'
  - 'https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js'
  - 'javascript/isotope.pkgd.min.js'
  - 'javascript/filtersamples.js'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
extra:
  telemetry: 'telemetry.sharepointpnp.com/powerplatform-samples'
  generator: false
  version: '1.0.0-0'
  social:
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/officedevpnp'
    - icon: 'fontawesome/brands/youtube'
      link: 'https://www.youtube.com/playlist?list=PLR9nK3mnD-OXgMjDBdjWUTRia89oixBhx'
    - icon: 'fontawesome/solid/link'
      link: 'https://aka.ms/sppnp'
repo_url: https://github.com/pnp/powerplatform-samples
edit_uri: tree/Docs/docs
site_url: https://pnp.github.io/pnp/powerplatform-samples/
site_favicon: favicon.ico
# dev_addr: '127.0.0.1:443'
